/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignInImport } from './routes/signIn'
import { Route as IndexImport } from './routes/index'
import { Route as LeagueJoinImport } from './routes/league_.join'
import { Route as LeagueCreateImport } from './routes/league_.create'
import { Route as LeagueLeagueIdImport } from './routes/league_.$leagueId'
import { Route as LeagueLeagueIdSettingsImport } from './routes/league_.$leagueId_.settings'
import { Route as LeagueLeagueIdJoinImport } from './routes/league_.$leagueId_.join'

// Create/Update Routes

const SignInRoute = SignInImport.update({
  id: '/signIn',
  path: '/signIn',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LeagueJoinRoute = LeagueJoinImport.update({
  id: '/league_/join',
  path: '/league/join',
  getParentRoute: () => rootRoute,
} as any)

const LeagueCreateRoute = LeagueCreateImport.update({
  id: '/league_/create',
  path: '/league/create',
  getParentRoute: () => rootRoute,
} as any)

const LeagueLeagueIdRoute = LeagueLeagueIdImport.update({
  id: '/league_/$leagueId',
  path: '/league/$leagueId',
  getParentRoute: () => rootRoute,
} as any)

const LeagueLeagueIdSettingsRoute = LeagueLeagueIdSettingsImport.update({
  id: '/league_/$leagueId_/settings',
  path: '/league/$leagueId/settings',
  getParentRoute: () => rootRoute,
} as any)

const LeagueLeagueIdJoinRoute = LeagueLeagueIdJoinImport.update({
  id: '/league_/$leagueId_/join',
  path: '/league/$leagueId/join',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/signIn': {
      id: '/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/league_/$leagueId': {
      id: '/league_/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof LeagueLeagueIdImport
      parentRoute: typeof rootRoute
    }
    '/league_/create': {
      id: '/league_/create'
      path: '/league/create'
      fullPath: '/league/create'
      preLoaderRoute: typeof LeagueCreateImport
      parentRoute: typeof rootRoute
    }
    '/league_/join': {
      id: '/league_/join'
      path: '/league/join'
      fullPath: '/league/join'
      preLoaderRoute: typeof LeagueJoinImport
      parentRoute: typeof rootRoute
    }
    '/league_/$leagueId_/join': {
      id: '/league_/$leagueId_/join'
      path: '/league/$leagueId/join'
      fullPath: '/league/$leagueId/join'
      preLoaderRoute: typeof LeagueLeagueIdJoinImport
      parentRoute: typeof rootRoute
    }
    '/league_/$leagueId_/settings': {
      id: '/league_/$leagueId_/settings'
      path: '/league/$leagueId/settings'
      fullPath: '/league/$leagueId/settings'
      preLoaderRoute: typeof LeagueLeagueIdSettingsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signIn': typeof SignInRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
  '/league/create': typeof LeagueCreateRoute
  '/league/join': typeof LeagueJoinRoute
  '/league/$leagueId/join': typeof LeagueLeagueIdJoinRoute
  '/league/$leagueId/settings': typeof LeagueLeagueIdSettingsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signIn': typeof SignInRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
  '/league/create': typeof LeagueCreateRoute
  '/league/join': typeof LeagueJoinRoute
  '/league/$leagueId/join': typeof LeagueLeagueIdJoinRoute
  '/league/$leagueId/settings': typeof LeagueLeagueIdSettingsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/signIn': typeof SignInRoute
  '/league_/$leagueId': typeof LeagueLeagueIdRoute
  '/league_/create': typeof LeagueCreateRoute
  '/league_/join': typeof LeagueJoinRoute
  '/league_/$leagueId_/join': typeof LeagueLeagueIdJoinRoute
  '/league_/$leagueId_/settings': typeof LeagueLeagueIdSettingsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signIn'
    | '/league/$leagueId'
    | '/league/create'
    | '/league/join'
    | '/league/$leagueId/join'
    | '/league/$leagueId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signIn'
    | '/league/$leagueId'
    | '/league/create'
    | '/league/join'
    | '/league/$leagueId/join'
    | '/league/$leagueId/settings'
  id:
    | '__root__'
    | '/'
    | '/signIn'
    | '/league_/$leagueId'
    | '/league_/create'
    | '/league_/join'
    | '/league_/$leagueId_/join'
    | '/league_/$leagueId_/settings'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  LeagueLeagueIdRoute: typeof LeagueLeagueIdRoute
  LeagueCreateRoute: typeof LeagueCreateRoute
  LeagueJoinRoute: typeof LeagueJoinRoute
  LeagueLeagueIdJoinRoute: typeof LeagueLeagueIdJoinRoute
  LeagueLeagueIdSettingsRoute: typeof LeagueLeagueIdSettingsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  LeagueLeagueIdRoute: LeagueLeagueIdRoute,
  LeagueCreateRoute: LeagueCreateRoute,
  LeagueJoinRoute: LeagueJoinRoute,
  LeagueLeagueIdJoinRoute: LeagueLeagueIdJoinRoute,
  LeagueLeagueIdSettingsRoute: LeagueLeagueIdSettingsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/signIn",
        "/league_/$leagueId",
        "/league_/create",
        "/league_/join",
        "/league_/$leagueId_/join",
        "/league_/$leagueId_/settings"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/signIn": {
      "filePath": "signIn.tsx"
    },
    "/league_/$leagueId": {
      "filePath": "league_.$leagueId.tsx"
    },
    "/league_/create": {
      "filePath": "league_.create.tsx"
    },
    "/league_/join": {
      "filePath": "league_.join.tsx"
    },
    "/league_/$leagueId_/join": {
      "filePath": "league_.$leagueId_.join.tsx"
    },
    "/league_/$leagueId_/settings": {
      "filePath": "league_.$leagueId_.settings.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
